services:
  - type: web
    name: webrtc-signalling-server
    env: rust
    region: oregon 
    plan: free 
    buildCommand: cd signalling-server && cargo build --release
    startCommand: cd signalling-server && ./target/release/signalling-server
    envVars:
      - key: RUST_LOG
        value: info
      - key: RUST_BACKTRACE
        value: "1"
